version: '3.6'
services:
  web:
    image: kaviuln/new_image
    ports:
      - 1370:1334
    restart: unless-stopped
    healthcheck:
     test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
